print("=====================================================")
print("=====================================================")
print(".....................................................")
print("Verse Interpreter w/GUI v1.0........................ ")
print(".....................................................")
print("A Verse programming sandbox independent of UEFN!.....")
print(".....................................................")
print(".....................................................")
print("Frontend & GUI by Cruz Wootten aka Lil Wikipedia.....")
print("Backend by Kariyampalli Christy & Turobin-Ort Marcel.")
print("The interpreter was released under MIT license.......")
print(".....................................................")
print("=====================================================")
print("=====================================================")

